---
# tasks file for ansible_redis

- name: be sure redis is installed
  yum: pkg=redis state=installed
  tags: redis-server

- name: send redis service
  template: src=../templates/redis.service.j2 dest=/etc/systemd/system/redis.service
  args:
    mode: 0644
  tags: redis service
  notify:
    - reload services

- name: start redis service
  service: name=redis state=started
  args:
    enabled: true
  tags: redis-server

- name : send redis.conf
  copy: src=../files/redis.conf dest=/etc/redis.conf
  args:
    mode: 0644
    owner: redis
    group: redis
  tags: redis-server
  notify:
    - restart redis

- name: open port 6379
  firewalld: port=6379/tcp
  args:
    permanent: true 
    state: enabled
    zone: internal
  tags: redis-server